import { Bikedata } from "./types/domain";
import { Componenttype } from "./types/domain";

export const componentType: Componenttype = {
  type: "Rahmen",
  iconPath: "/src/assets/Bike Shop Icons [Converted]-02.svg"
}

export const bikes: Bikedata[] = [
  {
    bike: {
      manufacturer: "Merida",
      bikeModel: "CYCLO CROSS 9000",
      serialNumber: "89aisjdlfkasjdf",
      imagePath: "/bikeassets/Merida_Cyclo_Cross_9000.jpg",
      price: 3499,
      color: "schwarz (signalrot)",
      size: "XX",
      year: 2016,
      id: "838ece1033bf7c7468e873e79ba2a3ec"
    },
    parts: [
      {
        modelName: "CC Carbon Disk 15",
        type: "fork",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Rotor 160",
        type: "brake",
        manufacturer: "SRAM",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "CX One",
        type: "shiftlever",
        manufacturer: "SRAM",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Mud Wrestler 33 Fold",
        type: "wheel",
        manufacturer: "Maxxis",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "R23 Spline cen/disk F15 R12",
        type: "rim",
        manufacturer: "DT Swiss",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Kappa 3",
        type: "seat",
        manufacturer: "Prologo",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "carbon H SB15 27.2",
        type: "seatpost",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Aero 32 Allen ST",
        type: "seatclamp",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Road Pro Cassic OS",
        type: "handlebar",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "pro Carbon OS-5",
        type: "stem",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Road Pro 3D",
        type: "grip",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "BB410P/No.55E",
        type: "headset",
        manufacturer: "FSA",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "CX one lever",
        type: "brakelever",
        manufacturer: "SRAM",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "",
        type: "bottombracket",
        manufacturer: "SRAM",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Force CX1 40 (BB86)",
        type: "crankset",
        manufacturer: "SRAM",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "CS-5800-11 11-32",
        type: "sprockets",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "X11EL",
        type: "chain",
        manufacturer: "KMC",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },

    ]
  },
  {
    bike: {
      manufacturer: "Focus",
      bikeModel: "Jam2",
      serialNumber: "89aisjdlfkasjdf",
      imagePath: "/bikeassets/Focus-Jam2.png",
      price: 8999,
      color: "silver",
      size: "XX",
      year: 2024,
      id: "4243391df87e703d511b43df2552ee6b"
    },
    parts: [{
      modelName: "CC Carbon Disk 15",
      type: "fork",
      manufacturer: "Shimano",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Rotor 160",
      type: "brake",
      manufacturer: "SRAM",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "CX One",
      type: "shiftlever",
      manufacturer: "SRAM",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Mud Wrestler 33 Fold",
      type: "wheel",
      manufacturer: "Maxxis",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "R23 Spline cen/disk F15 R12",
      type: "rim",
      manufacturer: "DT Swiss",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Kappa 3",
      type: "seat",
      manufacturer: "Prologo",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "carbon H SB15 27.2",
      type: "seatpost",
      manufacturer: "Merida",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Aero 32 Allen ST",
      type: "seatclamp",
      manufacturer: "Merida",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Road Pro Cassic OS",
      type: "handlebar",
      manufacturer: "Merida",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "pro Carbon OS-5",
      type: "stem",
      manufacturer: "Merida",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Road Pro 3D",
      type: "grip",
      manufacturer: "Merida",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "BB410P/No.55E",
      type: "headset",
      manufacturer: "FSA",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "CX one lever",
      type: "brakelever",
      manufacturer: "SRAM",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "",
      type: "bottombracket",
      manufacturer: "SRAM",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "Force CX1 40 (BB86)",
      type: "crankset",
      manufacturer: "SRAM",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "CS-5800-11 11-32",
      type: "sprockets",
      manufacturer: "Shimano",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    {
      modelName: "X11EL",
      type: "chain",
      manufacturer: "KMC",
      serialNumber: "N/A",
      dateOfInstallation: "N/A",
      isStock: true,
    },
    ]
  }, {
    bike: {
      manufacturer: "ROSE",
      bikeModel: "Backroad AL GRX 610 1x12",
      serialNumber: "89aisjdlfkasjdf",
      imagePath: "/bikeassets/Rose-Backroad-AL-GRX-610-1x12.png",
      price: 2499,
      color: "roasted olive",
      size: "53",
      year: 2024,
      id: "d41d8cd98f00b204e9800998ecf8427e"
    },
    parts: [
      {
        modelName: 'Cross Backroad, Carbon 28"',
        type: "fork",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "GRX, ST-RX610 / BR-RX410, schwarz 1700mm",
        type: "shiftlever",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Terra Trail ProTection, Black / Transparent 40-584",
        type: "wheel",
        manufacturer: "Continental",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: 'G25, 27,5"',
        type: "rim",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Edition by Selle Italia, schwarz",
        type: "seat",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "WTB, 350mm, schwarz 27,2mm",
        type: "seatpost",
        manufacturer: "Ritchey",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "",
        type: "seatclamp",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Venture Max Comp, schwarz 40cm",
        type: "handlebar",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "ALR, schwarz sand 70mm",
        type: "stem",
        manufacturer: "ROSE",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Gel-Comfort, schwarz",
        type: "ROSE",
        manufacturer: "Merida",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "",
        type: "headset",
        manufacturer: "",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "GRX, BL-RX610-L / BR-RX410 1000mm",
        type: "brakelever",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "",
        type: "bottombracket",
        manufacturer: "",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "FC-RX610-1, 40Z, 170mm",
        type: "crankset",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "SLX, CS-M7100-12, 12-fach, 10-51",
        type: "sprockets",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },
      {
        modelName: "Deore CN-M6100, Quick Link, 12-fach 122gl.",
        type: "chain",
        manufacturer: "Shimano",
        serialNumber: "N/A",
        dateOfInstallation: "N/A",
        isStock: true,
      },

    ]
  }
];


